clear all
close all

% Want to extract only the green channel and then normalise this so that
% all images have the same mean intensity

texture_root = 'D:\simfiles\texture\greenOnlyNormalised\';

texture_names={'HDR_Botanic_RGB.png',....
    'HDR_Bushes_RGB.png',...
    'HDR_Car Park_RGB.png',...
    'HDR_Classroom_RGB.png',...
    'HDR_Creek Bed_RGB.png',...
    'HDR_Field_RGB.png',...
    'HDR_Fountain_RGB.png',...
    'HDR_Hill_RGB.png',...
    'HDR_House_RGB.png',...
    'HDR_Lab_RGB.png',...
    'HDR_Library_RGB.png',...
    'HDR_Lounge_RGB.png',...
    'HDR_Outdoor_RGB.png',...
    'HDR_Park_RGB.png',...
    'HDR_Rock Garden_RGB.png',...
    'HDR_Rubble_RGB.png',...
    'HDR_Shadow_RGB.png',...
    'HDR_Tree_RGB.png',...
    'HDR_Walkway_RGB.png'};

for t=1:numel(texture_names)
    input=imread([texture_root texture_names{t}]);
    greench=input(:,:,2);
    disp([num2str(min(greench(:))) ' ' num2str(max(greench(:))) ' ' num2str(mean(greench(:)))])
%     saveas
end